# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.2"
manifest_format = "2.0"
project_hash = "55bdd516f80d246af56e4c3f61fd8f01bbaf6a16"

[[deps.MonadInterface]]
git-tree-sha1 = "7e4db9bbbae34fafd2e4a8784e9755d8524ba299"
repo-rev = "main"
repo-url = "https://github.com/JuliaHybrid/MonadInterface.jl.git"
uuid = "4c81018e-a0fd-4a0d-a53b-43c59f4db333"
version = "0.1.0"
